# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deveco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualitedeveco',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name="Image principale de l'article (facultatif)"),
        ),
        migrations.AlterField(
            model_name='actualitedeveco',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='actualitedeveco',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='dirigeant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dirigeant',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Photo du dirigeant'),
        ),
        migrations.AlterField(
            model_name='documentattachedeveco',
            name='document',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documentattachedeveco',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name="Image / Logo de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
