# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('affgen', '0002_auto_20160927_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptrendu',
            name='date',
            field=models.DateField(verbose_name='Date du conseil'),
        ),
        migrations.AlterField(
            model_name='cptrendu',
            name='document',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Document PDF'),
        ),
        migrations.AlterField(
            model_name='cptrendu',
            name='entite',
            field=models.CharField(choices=[('vyvs', 'Val d’Yerres Val de Seine'), ('casvs', 'Val de Seine'), ('cavt', 'Val d’Yerres')], default='vyvs', max_length=5),
        ),
        migrations.AlterField(
            model_name='elu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='affgen', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='elu',
            name='sexe',
            field=models.CharField(choices=[('ind', 'Indeterminé'), ('homme', 'Homme'), ('femme', 'Femme')], default='ind', max_length=5),
        ),
        migrations.AlterField(
            model_name='mandatagglo',
            name='index',
            field=models.PositiveSmallIntegerField(verbose_name="ordre d'apparition"),
        ),
        migrations.AlterField(
            model_name='qualifmandat',
            name='index',
            field=models.PositiveSmallIntegerField(verbose_name="ordre d'apparition"),
        ),
        migrations.AlterField(
            model_name='titrehorsagglo',
            name='index',
            field=models.PositiveSmallIntegerField(verbose_name="ordre d'apparition"),
        ),
    ]
