# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affgen', '0003_auto_20170607_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptrendu',
            name='entite',
            field=models.CharField(choices=[('vyvs', 'Val d’Yerres Val de Seine'), ('casvs', 'Val de Seine'), ('cavy', 'Val d’Yerres')], default='vyvs', max_length=5),
        ),
    ]
