# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affgen', '0005_auto_20170915_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numreference', models.CharField(max_length=32, verbose_name='Numéro de référence')),
                ('titre', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/deliberations/', verbose_name='Fichier PDF')),
            ],
            options={
                'verbose_name': 'Délibération',
                'verbose_name_plural': 'Délibérations',
                'ordering': ['numreference'],
            },
        ),
        migrations.AlterModelOptions(
            name='cptrendu',
            options={'ordering': ['-date'], 'verbose_name': 'Compte rendu conseil', 'verbose_name_plural': 'Comptes rendus'},
        ),
        migrations.AlterField(
            model_name='cptrendu',
            name='document',
            field=models.FileField(max_length=200, upload_to='uploads/comptesrendus', verbose_name='Document PDF'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='compterendu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affgen.Cptrendu'),
        ),
    ]
