# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0004_auto_20160616_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='alertesreponses',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='alertesreponses',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Mail (facultatif)'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='fax',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Fax (facultatif)'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image (facultatif)'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(choices=[('bib', 'Bibliothèques/Médiatèques'), ('crd', 'Conservatoires'), ('aut', 'Autres')], default='aut', max_length=3),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='equipementfonction',
            name='logo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='equipementfonction',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='equipementfonction',
            name='picto',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Pictogramme pour geolocalisation'),
        ),
        migrations.AlterField(
            model_name='equipementfonction',
            name='pluriel',
            field=models.CharField(max_length=255, verbose_name='Nom de la fonction au pluriel'),
        ),
        migrations.AlterField(
            model_name='equipementfonction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Service Gestionnaire'),
        ),
        migrations.AlterField(
            model_name='facilite',
            name='importance',
            field=models.IntegerField(verbose_name="Degrée d'importance (de 0 + important à 100 - important ). Entre 0 et 20 c'est géolocalisable au delà de 20 non."),
        ),
        migrations.AlterField(
            model_name='facilite',
            name='picto',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Pictogramme'),
        ),
        migrations.AlterField(
            model_name='facilite',
            name='picto_geoloc',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Pictogramme pour la géolocalisation'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='Désignation : (ex: "Entrée Adulte ")'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='index',
            field=models.IntegerField(verbose_name="Ordre d'apparition (0 = en haut de liste)"),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='info_additionelle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Infos additionelles : (facultatif)'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='prix_non_residents',
            field=models.FloatField(verbose_name='Tarif non résidents ( 0 = gratuit  )'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='prix_residents',
            field=models.FloatField(verbose_name='Tarif résidents ( 0 = gratuit  )'),
        ),
        migrations.AlterField(
            model_name='tarifcategorie',
            name='equipement_fonction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.EquipementFonction', verbose_name="Catégorie d'équipement concernée"),
        ),
        migrations.AlterField(
            model_name='tarifcategorie',
            name='index',
            field=models.IntegerField(verbose_name="Ordre d'apparition (0 = le plus important et tarif de base affiché pour l'équipement)"),
        ),
        migrations.AlterField(
            model_name='tarifcategorie',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Catégorie de tarif'),
        ),
        migrations.AlterField(
            model_name='tarifspecifique',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='Désignation : (ex: "Entrée Adulte ")'),
        ),
        migrations.AlterField(
            model_name='tarifspecifique',
            name='index',
            field=models.IntegerField(verbose_name="Ordre d'apparition (0 = en haut de liste)"),
        ),
        migrations.AlterField(
            model_name='tarifspecifique',
            name='info_additionelle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Infos additionelles : (facultatif)'),
        ),
        migrations.AlterField(
            model_name='tarifspecifique',
            name='prix_non_residents',
            field=models.FloatField(verbose_name='Tarif non résidents ( 0 = gratuit  )'),
        ),
        migrations.AlterField(
            model_name='tarifspecifique',
            name='prix_residents',
            field=models.FloatField(verbose_name='Tarif résidents ( 0 = gratuit  )'),
        ),
    ]
