# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0005_auto_20170607_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementfonction',
            name='schema_url',
            field=models.URLField(default='http://schema.org/Place', verbose_name='Schema URL'),
        ),
    ]
