# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 13:47
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0006_equipementfonction_schema_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementfonction',
            name='logo',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200, verbose_name='Logo'),
        ),
    ]
