# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisations', '0003_auto_20160927_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
