# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localisations', '0004_auto_20170607_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ville',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Villes'},
        ),
    ]
