# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0006_auto_20170607_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saison',
            options={'ordering': ['-debut']},
        ),
        migrations.AlterModelOptions(
            name='saisonculturelle',
            options={},
        ),
    ]
