# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0007_auto_20170824_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementMde',
            fields=[
            ],
            options={
                'verbose_name': 'Événement MDE',
                'verbose_name_plural': 'Événements MDE',
                'proxy': True,
            },
            bases=('evenements.evenement',),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='categorie',
            field=models.CharField(choices=[('bib', 'Bibliothèques/Médiatèques'), ('crd', 'Conservatoires'), ('sty', 'Sothevy'), ('eco', 'Développement Économique'), ('mde', "Maison de l'environnement"), ('aut', 'Autres')], default='aut', max_length=3),
        ),
    ]
