# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 13:47
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0008_auto_20170929_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=255, verbose_name='Image (facultatif)'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='logo',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=255, verbose_name='Image'),
        ),
    ]
