# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0009_auto_20180327_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='organisateur',
            field=models.ManyToManyField(blank=True, null=True, to='evenements.Organisateur'),
        ),
    ]
