# MailJet
#MAILJET_API_KEY='YOUR_API_KEY'
#MAILJET_SECRET_KEY='YOUR_SECRET_KEY'
#MAIL_LIST_ID='ID'
MAILJET_API_KEY='API KEY'
MAILJET_SECRET_KEY='SECRET KEY'
MAIL_LIST_ID='MAIl LIST ID'

NOM_DOMAINE = 'http://127.0.0.1:8080'
