# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epn', '0002_ficheinscription_numero_adherent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheinscription',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire, usage administratif uniquement pas de commentaires sur la personalité'),
        ),
        migrations.AlterField(
            model_name='ficheinscription',
            name='dateinscription',
            field=models.DateTimeField(),
        ),
    ]
