# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattache',
            name='document',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documentattache',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='pagestatiqueservice',
            name='index',
            field=models.IntegerField(verbose_name='Ordre apparition dans la liste'),
        ),
        migrations.AlterField(
            model_name='pagestatiqueservice',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='pagestatiqueservice',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='service',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
