# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_auto_20150930_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='page_accueil',
            field=models.BooleanField(default=False, verbose_name="Affichage en page d'accueil ?"),
        ),
        migrations.AlterField(
            model_name='documentattache',
            name='document',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documentattache',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='document',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Document PDF'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, upload_to='magazines/img'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='newsletterbib',
            name='edito',
            field=models.TextField(blank=True, verbose_name='Edito'),
        ),
        migrations.AlterField(
            model_name='newsletterbib',
            name='evenement_debut',
            field=models.DateField(verbose_name='Date de Début des événements'),
        ),
        migrations.AlterField(
            model_name='newsletterbib',
            name='evenement_fin',
            field=models.DateField(verbose_name='Date de fin des événements'),
        ),
        migrations.AlterField(
            model_name='newsletterbib',
            name='maj',
            field=models.DateField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='pagebase',
            name='carroussel',
            field=models.BooleanField(default=False, verbose_name="Présence dans le carroussel de la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='pagebase',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name="Image principale de l'article (facultatif)"),
        ),
        migrations.AlterField(
            model_name='pagebase',
            name='index_carroussel',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage dans le caroussel (0 = premier)"),
        ),
        migrations.AlterField(
            model_name='pagebase',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='pagebase',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='pagestatique',
            name='note_page_accueil',
            field=models.BooleanField(default=False, verbose_name="Lister dans les notes de la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='document',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Document PDF'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='image',
            field=models.ImageField(upload_to='rapports/img'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='titre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titre'),
        ),
    ]
