# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='id_allocine_cine',
            field=models.CharField(max_length=255, verbose_name='Identifiant Allociné'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cinemas', verbose_name='Photo du lieu'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='meta_description',
            field=models.CharField(max_length=255, verbose_name='Méta description'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='telephone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duree',
            field=models.IntegerField(verbose_name='Durée du film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='id_allocine_film',
            field=models.CharField(max_length=255, verbose_name='Identifiant Allociné du Film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cinema', verbose_name='Affiche du film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='note',
            field=models.FloatField(default=0, verbose_name='Note des utilisateurs allociné'),
        ),
        migrations.AlterField(
            model_name='film',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='url_allocine_image',
            field=models.URLField(verbose_name='URL affiche du film sur allociné'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='date_debut',
            field=models.DateTimeField(verbose_name='Date et heure de début du film'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='date_fin',
            field=models.DateTimeField(verbose_name='Date et heure de fin du film'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format ( facultatif )'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='id_allocine_film',
            field=models.CharField(max_length=255, verbose_name='Identifiant Allociné du Film'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='version_lang',
            field=models.CharField(max_length=255, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='version_vo',
            field=models.BooleanField(default=False, verbose_name='Version originale'),
        ),
    ]
