# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncesemploi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='contact',
            field=models.TextField(blank=True, verbose_name='Contact:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='deplacement',
            field=models.TextField(blank=True, verbose_name='Déplacement:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='description_du_poste',
            field=models.TextField(blank=True, verbose_name='Description du poste:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='experience_requise',
            field=models.TextField(blank=True, verbose_name='Expérience requise:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='intitule',
            field=models.CharField(max_length=255, verbose_name='Intitulé:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='lieu_travail',
            field=models.TextField(blank=True, verbose_name='Lieu de travail:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='nb_postes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de postes:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='niveau_formation',
            field=models.TextField(blank=True, verbose_name='Niveau de formation requis:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='nom_employeur',
            field=models.TextField(blank=True, verbose_name="Nom de l'employeur:"),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='publication'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='salaire_indicatif',
            field=models.CharField(blank=True, max_length=255, verbose_name='Salaire indicatif:'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité:"),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='type_de_poste',
            field=models.CharField(blank=True, max_length=255, verbose_name='Type de Poste:'),
        ),
        migrations.AlterField(
            model_name='importgidem',
            name='fichier_xls',
            field=models.FileField(upload_to='annoncesemploi/importsgidem/%Y/%m/%d'),
        ),
    ]
